apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: yoyota/python-flask-starter
deploy:
  helm:
    releases:
      - name: python-flask-starter
        namespace: yoyota
        chartPath: helm
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.DIGEST_HEX}}"
